### ISSUE TITLE
Systematic crash when deleting input containing unicode characters 

### ISSUE THREAD

**Issue by MrCasCode** [sayanarijit/tui-input#4]
Hi @sayanarijit 

Thank you very much for this amazing crate.

I'm encountering a systematic crash whenever I write strings containing unicode characters. 

It's crashing on 
`input.rs: 115: self.value.remove(self.cursor);`

A minimum reproducible example is:
```
let mut string = "¡¡¡¡".to_string();
string.remove(1);
```

`thread 'main' panicked at 'byte index 1 is not a char boundary; it is inside '¡' (bytes 0..2) of `¡¡¡¡`'`

For now just creating the issue to signal the weakness. I'll create a PR if I find a clean solution

**Comment by sayanarijit** [comment]
Thanks for reporting. Released 0.2.0 with the fix.
